<?xml version="1.0" encoding="UTF-8"?>

<ClassDiagram name="EVA3_7_THROW_EXCEPTION">
  <ClassDiagramComponents>
    <Class name="EVA3_7_THROW_EXCEPTION" package="eva3_7_throw_exception" visibility="public" xPosition="20.0" yPosition="20.0">
      <Fields/>
      <Constructors/>
      <Methods>
        <Method name="main" returnType="void" visibility="public" isStatic="true">
          <Argument type="String[]" name="args"/>
        </Method>
      </Methods>
    </Class>
    <Class name="Prueba" package="eva3_7_throw_exception" visibility="public" xPosition="320.0" yPosition="20.0">
      <Fields>
        <Field name="valor" type="int" visibility="private"/>
      </Fields>
      <Constructors/>
      <Methods>
        <Method name="getValor" returnType="int" visibility="public"/>
        <Method name="setValor" returnType="void" visibility="public">
          <Argument type="int" name="valor"/>
        </Method>
      </Methods>
    </Class>
  </ClassDiagramComponents>
  <ClassDiagramRelations/>
</ClassDiagram>
